server: 
  port: 9999
spring: 
  datasource: 
    continue-on-error: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    eureka: 
      client: 
        serviceUrl: 
          defaultZone: "http://localhost:8761/eureka/"
    initialize: true
    logging: 
      level: 
        ROOT: INFO
    password: root
    schema: "classpath:/mysql.sql"
    sleuth: 
      enabled: false
    url: "jdbc:mysql://${MYSQL_HOST:localhost}/zipkin?autoReconnect=true&useSSL=false"
    username: root
    zipkin: 
      storage: 
        type: mysql
  rabbitmq: 
    host: localhost
    port: 5672
